# config/packages/rate_limiter.yaml
framework:
    rate_limiter:
        location_tracking:
            policy: 'fixed_window'
            limit: 1
            interval: '30 seconds'
            lock_factory: null

when@test:
    framework:
        rate_limiter:
            location_tracking:
                policy: 'fixed_window'
                limit: 100
                interval: '1 seconds'
                lock_factory: null
                storage_service: 'App\Component\RateLimiter\TestStorage'
